name: version update check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run bot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python main.py
